USE ROLE Flight_ROLE;
USE WAREHOUSE Flight_WH;
USE DATABASE Flight_DB;

CREATE OR REPLACE VIEW ANALYTICS.FLIGHT_CONSUMPTION_ANALYTICS AS
SELECT
    f.FLIGHT_NUMBER,
    f.DEPARTURE_COUNTRY_CODE,
    SUM(f.ACTUAL_TOTAL_SEATS) as Total_Seats,
    e.aircraft_type,
    e.DEPARTURE_AIRPORT,
    e.ARRIVAL_AIRPORT,
    SUM(e.ESTIMATED_FUEL_BURN_TOTAL_TONNES) AS total_fuel_burn,
    SUM(e.ESTIMATED_CO2_TOTAL_TONNES) AS total_co2_emission
FROM
    FLIGHT_STATUS.FLIGHT_STATUS_DATA f
JOIN
    FLIGHT_EMISSION.FLIGHT_EMISSION_DATA e
ON
    CAST(f.FLIGHT_NUMBER AS VARCHAR)= e.FLIGHT_NUMBER
    AND f.DEPARTURE_IATA_AIRPORT_CODE = e.DEPARTURE_AIRPORT
    AND f.ARRIVAL_IATA_AIRPORT_CODE = e.ARRIVAL_AIRPORT
WHERE
    f.IS_OPERATING_CARRIER = TRUE
    AND e.ESTIMATED_FUEL_BURN_TOTAL_TONNES IS NOT NULL
    AND f.ACTUAL_TOTAL_SEATS IS NOT NULL
GROUP BY
    f.FLIGHT_NUMBER,
    f.DEPARTURE_COUNTRY_CODE,
    f.ARRIVAL_COUNTRY_CODE,
    e.aircraft_type,
    e.DEPARTURE_AIRPORT;
