snowsql_config_path = "~/.snowsql/config"
snowsql_connection_name = "dev"

[default]
input_parameters = "['STRING']"
return_type = "FLOAT"
file = "app.zip"
name = "get_efficiency_score"
handler = "app.main"
execute_as_caller = true

[dev]
database = "Flight_DB"
schema = "FLIGHT_ANALYTICS"
warehouse = "Flight_WH"
role = "Flight_Role"
overwrite = true