USE ROLE Flight_ROLE;
USE WAREHOUSE Flight_WH;
USE DATABASE Flight_DB;

CREATE OR REPLACE VIEW ANALYTICS.COMBINED_FLIGHT_ANALYSIS AS
SELECT
    s.FLIGHT_NUMBER,
    s.DEPARTURE_COUNTRY_CODE,
    s.ARRIVAL_COUNTRY_CODE,
    s.DEPARTURE_IATA_AIRPORT_CODE AS departure_terminal,
    g.LEG_1_DEPARTURE_AIRPORT_IATA AS layover_start_terminal,
    g.LEG_2_DEPARTURE_AIRPORT_IATA AS layover_end_terminal,
    s.ARRIVAL_IATA_AIRPORT_CODE AS arrival_terminal,
    s.FLIGHT_STATE,
    s.SCHEDULED_DEPARTURE_TIME_LOCAL,
    s.SCHEDULED_ARRIVAL_TIME_LOCAL,
    g.CONNECTION_ID,
    AVG(g.ELAPSED_TIME) AS avg_connection_elapsed_time,
    g.FREQUENCY,
    g.LEG_1_DISTANCE + g.LEG_2_DISTANCE AS total_route_distance,
    e.AIRCRAFT_TYPE,
    e.AIRCRAFT_REGISTRATION_NUMBER,
    e.MISSING_ACTUAL_TIMES,
    e.IS_OPERATING,
    MAX(s.ACTUAL_TOTAL_SEATS) AS max_seats,
    MIN(s.ACTUAL_TOTAL_SEATS) AS min_seats
FROM
    FLIGHT_STATUS.FLIGHT_STATUS_DATA s
JOIN
    FLIGHT_EMISSION.FLIGHT_EMISSION_DATA e ON CAST(s.FLIGHT_NUMBER AS VARCHAR) = e.FLIGHT_NUMBER
JOIN
    FLIGHT_GLOBAL_CONNECTION.FLIGHT_GLOBAL_CONNECTION_DATA g ON e.DEPARTURE_AIRPORT = g.DEPARTURE_AIRPORT_IATA AND e.ARRIVAL_AIRPORT = g.ARRIVAL_AIRPORT_IATA
GROUP BY
    s.FLIGHT_NUMBER,
    s.DEPARTURE_COUNTRY_CODE,
    s.ARRIVAL_COUNTRY_CODE,
    s.DEPARTURE_IATA_AIRPORT_CODE,
    g.LEG_1_DEPARTURE_AIRPORT_IATA,
    g.LEG_2_DEPARTURE_AIRPORT_IATA,
    s.ARRIVAL_IATA_AIRPORT_CODE,
    s.FLIGHT_STATE,
    s.SCHEDULED_DEPARTURE_TIME_LOCAL,
    s.SCHEDULED_ARRIVAL_TIME_LOCAL,
    g.CONNECTION_ID,
    g.FREQUENCY,
    g.LEG_1_DISTANCE,
    g.LEG_2_DISTANCE,
    e.AIRCRAFT_TYPE,
    e.AIRCRAFT_REGISTRATION_NUMBER,
    e.MISSING_ACTUAL_TIMES,
    e.IS_OPERATING;